#Type Name        ID      GECOS                      Home-dir     Shell

u! guixbuild01    -       "Static guix builder_01"   /var/empty   /bin/nologin
u! guixbuild02    -       "Static guix builder_02"   /var/empty   /bin/nologin
u! guixbuild03    -       "Static guix builder_03"   /var/empty   /bin/nologin
u! guixbuild04    -       "Static guix builder_04"   /var/empty   /bin/nologin
u! guixbuild05    -       "Static guix builder_05"   /var/empty   /bin/nologin
u! guixbuild06    -       "Static guix builder_06"   /var/empty   /bin/nologin
u! guixbuild07    -       "Static guix builder_07"   /var/empty   /bin/nologin
u! guixbuild08    -       "Static guix builder_08"   /var/empty   /bin/nologin
u! guixbuild09    -       "Static guix builder_09"   /var/empty   /bin/nologin
u! guixbuild10    -       "Static guix builder_10"   /var/empty   /bin/nologin
u! guixbuild11    -       "Static guix builder_11"   /var/empty   /bin/nologin
u! guixbuild12    -       "Static guix builder_12"   /var/empty   /bin/nologin
u! guixbuild13    -       "Static guix builder_13"   /var/empty   /bin/nologin
u! guixbuild14    -       "Static guix builder_14"   /var/empty   /bin/nologin
u! guixbuild15    -       "Static guix builder_15"   /var/empty   /bin/nologin
u! guixbuild16    -       "Static guix builder_16"   /var/empty   /bin/nologin
u! guixbuild17    -       "Static guix builder_17"   /var/empty   /bin/nologin
u! guixbuild18    -       "Static guix builder_18"   /var/empty   /bin/nologin
u! guixbuild19    -       "Static guix builder_19"   /var/empty   /bin/nologin
u! guixbuild20    -       "Static guix builder_20"   /var/empty   /bin/nologin
u! guixbuild21    -       "Static guix builder_21"   /var/empty   /bin/nologin
u! guixbuild22    -       "Static guix builder_22"   /var/empty   /bin/nologin
u! guixbuild23    -       "Static guix builder_23"   /var/empty   /bin/nologin
u! guixbuild24    -       "Static guix builder_24"   /var/empty   /bin/nologin
u! guixbuild25    -       "Static guix builder_25"   /var/empty   /bin/nologin
u! guixbuild26    -       "Static guix builder_26"   /var/empty   /bin/nologin
u! guixbuild27    -       "Static guix builder_27"   /var/empty   /bin/nologin
u! guixbuild28    -       "Static guix builder_28"   /var/empty   /bin/nologin
u! guixbuild29    -       "Static guix builder_29"   /var/empty   /bin/nologin
u! guixbuild30    -       "Static guix builder_30"   /var/empty   /bin/nologin
u! guixbuild31    -       "Static guix builder_31"   /var/empty   /bin/nologin
u! guixbuild32    -       "Static guix builder_32"   /var/empty   /bin/nologin

m guixbuild01 guixbuild
m guixbuild02 guixbuild
m guixbuild03 guixbuild
m guixbuild04 guixbuild
m guixbuild05 guixbuild
m guixbuild06 guixbuild
m guixbuild07 guixbuild
m guixbuild08 guixbuild
m guixbuild09 guixbuild
m guixbuild10 guixbuild
m guixbuild11 guixbuild
m guixbuild12 guixbuild
m guixbuild13 guixbuild
m guixbuild14 guixbuild
m guixbuild15 guixbuild
m guixbuild16 guixbuild
m guixbuild17 guixbuild
m guixbuild18 guixbuild
m guixbuild19 guixbuild
m guixbuild20 guixbuild
m guixbuild21 guixbuild
m guixbuild22 guixbuild
m guixbuild23 guixbuild
m guixbuild24 guixbuild
m guixbuild25 guixbuild
m guixbuild26 guixbuild
m guixbuild27 guixbuild
m guixbuild28 guixbuild
m guixbuild29 guixbuild
m guixbuild30 guixbuild
m guixbuild31 guixbuild
m guixbuild32 guixbuild
